### ISSUE TITLE
Failed to replace layer_norm of type T5LayerNorm with T5LayerNorm

### ISSUE THREAD

**Issue by wang-kangkang** [flymin/MagicDriveDiT#10]
[rank3]: Traceback (most recent call last):
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/sharder.py", line 197, in _replace_sub_module
[rank3]:     replace_layer = target_module.from_native_module(
[rank3]:   File "/root/projects/magicdriveDiT/MagicDriveDiT/./magicdrivedit/acceleration/shardformer/modeling/t5.py", line 31, in from_native_module
[rank3]:     assert module.__class__.__name__ == "FusedRMSNorm", (
[rank3]: AssertionError: Recovering T5LayerNorm requires the original layer to be apex's Fused RMS Norm.Apex's fused norm is automatically used by Hugging Face Transformers https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L265C5-L265C48

[rank3]: During handling of the above exception, another exception occurred:

[rank3]: Traceback (most recent call last):
[rank3]:   File "/root/projects/magicdriveDiT/MagicDriveDiT/scripts/train_magicdrive.py", line 736, in <module>
[rank3]:     main()
[rank3]:   File "/root/projects/magicdriveDiT/MagicDriveDiT/scripts/train_magicdrive.py", line 263, in main
[rank3]:     text_encoder = build_module(cfg.get("text_encoder", None), MODELS, device=device, dtype=dtype)
[rank3]:   File "/root/projects/magicdriveDiT/MagicDriveDiT/./magicdrivedit/registry.py", line 24, in build_module
[rank3]:     return builder.build(cfg)
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
[rank3]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[rank3]:     obj = obj_cls(**args)  # type: ignore
[rank3]:   File "/root/projects/magicdriveDiT/MagicDriveDiT/./magicdrivedit/models/text_encoder/t5.py", line 165, in __init__
[rank3]:     self.shardformer_t5()
[rank3]:   File "/root/projects/magicdriveDiT/MagicDriveDiT/./magicdrivedit/models/text_encoder/t5.py", line 184, in shardformer_t5
[rank3]:     optim_model, _ = shard_former.optimize(self.t5.model, policy=T5EncoderPolicy())
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/shardformer.py", line 55, in optimize
[rank3]:     shared_params = sharder.shard()
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/sharder.py", line 43, in shard
[rank3]:     self._replace_module(include=held_layers)
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/sharder.py", line 67, in _replace_module
[rank3]:     self._recursive_replace_layer(
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/sharder.py", line 115, in _recursive_replace_layer
[rank3]:     self._recursive_replace_layer(
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/sharder.py", line 115, in _recursive_replace_layer
[rank3]:     self._recursive_replace_layer(
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/sharder.py", line 115, in _recursive_replace_layer
[rank3]:     self._recursive_replace_layer(
[rank3]:   [Previous line repeated 2 more times]
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/sharder.py", line 112, in _recursive_replace_layer
[rank3]:     self._replace_sub_module(module, sub_module_replacement, include)
[rank3]:   File "/root/projects/magicdriveDiT/anaconda3/lib/python3.9/site-packages/colossalai-0.4.3-py3.9.egg/colossalai/shardformer/shard/sharder.py", line 201, in _replace_sub_module
[rank3]:     raise RuntimeError(
[rank3]: RuntimeError: Failed to replace layer_norm of type T5LayerNorm with T5LayerNorm with the exception: Recovering T5LayerNorm requires the original layer to be apex's Fused RMS Norm.Apex's fused norm is automatically used by Hugging Face Transformers https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L265C5-L265C48. Please check your model configuration or sharding policy, you can set up an issue for us to help you as well.

apex installation is correct，how to solve this problem?

`Package                        Version
------------------------------ --------------------
absl-py                        1.4.0
accelerate                     0.29.3
addict                         2.4.0
aiohttp                        3.8.1
aiosignal                      1.3.1
alabaster                      0.7.12
anaconda-client                1.9.0
anaconda-navigator             2.1.4
anaconda-project               0.10.2
annotated-types                0.7.0
antlr4-python3-runtime         4.9.3
anyio                          4.4.0
anykeystore                    0.2
apex                           0.1
appdirs                        1.4.4
argon2-cffi                    21.3.0
argon2-cffi-bindings           21.2.0
arrow                          1.2.2
astroid                        2.6.6
astropy                        5.0.4
asttokens                      2.0.5
async-timeout                  4.0.1
atomicwrites                   1.4.0
attrs                          23.2.0
Automat                        20.2.0
autopep8                       1.6.0
Babel                          2.9.1
backcall                       0.2.0
backports.functools-lru-cache  1.6.4
backports.tempfile             1.0
backports.weakref              1.0.post1
bcrypt                         4.1.3
beartype                       0.18.5
beautifulsoup4                 4.12.3
binaryornot                    0.4.4
bitarray                       2.4.1
bitsandbytes                   0.42.0
bkcharts                       0.2
black                          19.10b0
bleach                         4.1.0
blinker                        1.9.0
bokeh                          2.4.2
boto3                          1.21.32
botocore                       1.24.32
Bottleneck                     1.3.4
brotlipy                       0.7.0
cachetools                     4.2.4
certifi                        2023.7.22
cffi                           1.17.1
cfgv                           3.4.0
chardet                        4.0.0
charset-normalizer             3.2.0
click                          8.1.7
cloudpickle                    2.0.0
clyent                         1.2.2
colorama                       0.4.4
colorcet                       2.0.6
colossalai                     0.4.3
conda                          4.12.0
conda-build                    3.21.8
conda-content-trust            0+unknown
conda-pack                     0.6.0
conda-package-handling         1.8.1
conda-repo-cli                 1.0.4
conda-token                    0.3.0
conda-verify                   3.4.2
constantly                     15.1.0
contexttimer                   0.3.3
contourpy                      1.1.0
cookiecutter                   1.7.3
cryptacular                    1.6.2
cryptography                   41.0.7
cssselect                      1.1.0
cxxfilt                        0.3.0
cycler                         0.11.0
Cython                         0.29.28
cytoolz                        0.11.0
daal4py                        2021.5.0
dask                           2022.2.1
datashader                     0.13.0
datashape                      0.5.4
debugpy                        1.6.7
decorator                      4.4.2
defusedxml                     0.7.1
Deprecated                     1.2.14
descartes                      1.1.0
diff-match-patch               20200713
diffusers                      0.30.0
distlib                        0.3.8
distributed                    2022.2.1
dnspython                      2.7.0
docutils                       0.17.1
einops                         0.8.0
email_validator                2.2.0
entrypoints                    0.4
et-xmlfile                     1.1.0
exceptiongroup                 1.2.2
executing                      0.8.3
fabric                         3.0.0
fastapi                        0.111.1
fastapi-cli                    0.0.6
fastjsonschema                 2.15.1
filelock                       3.12.2
fire                           0.6.0
flake8                         3.9.2
flash-attn                     2.6.3
Flask                          2.0.1
fonttools                      4.41.1
frozenlist                     1.4.1
fsspec                         2024.6.0
ftfy                           6.2.0
future                         0.18.2
galore-torch                   1.0
gensim                         4.1.2
glob2                          0.7
gmpy2                          2.1.2
google                         3.0.0
google-api-core                1.25.1
google-auth                    1.33.0
google-auth-oauthlib           0.4.6
google-cloud-core              1.7.1
google-cloud-storage           1.31.0
google-crc32c                  1.1.2
google-resumable-media         1.3.1
googleapis-common-protos       1.53.0
greenlet                       1.1.1
grpcio                         1.56.2
h11                            0.14.0
h5py                           3.11.0
HeapDict                       1.0.1
holoviews                      1.14.8
httpcore                       1.0.7
httptools                      0.6.4
httpx                          0.28.1
huggingface-hub                0.23.4
hupper                         1.12.1
hvplot                         0.7.3
hydra-core                     1.3.0
hyperlink                      21.0.0
identify                       2.5.36
idna                           3.4
imagecodecs                    2021.8.26
imageio                        2.34.1
imageio-ffmpeg                 0.5.1
imagesize                      1.3.0
importlib_metadata             7.1.0
importlib_resources            6.4.5
incremental                    21.3.0
inflection                     0.5.1
iniconfig                      1.1.1
intake                         0.6.5
intervaltree                   3.1.0
invoke                         2.2.0
ipykernel                      6.9.1
ipython                        8.2.0
ipython-genutils               0.2.0
ipywidgets                     7.6.5
isort                          5.9.3
itemadapter                    0.3.0
itemloaders                    1.0.4
itsdangerous                   2.1.2
jdcal                          1.4.1
jedi                           0.18.1
jeepney                        0.7.1
Jinja2                         3.0.1
jinja2-time                    0.2.0
jmespath                       0.10.0
joblib                         1.3.1
json5                          0.9.6
jsonschema                     4.4.0
jupyter                        1.0.0
jupyter-client                 6.1.12
jupyter-console                6.4.0
jupyter-core                   4.9.2
jupyter-server                 1.13.5
jupyterlab                     3.3.2
jupyterlab-pygments            0.1.2
jupyterlab-server              2.10.3
jupyterlab-widgets             1.0.0
keyring                        23.4.0
kiwisolver                     1.3.2
lazy-object-proxy              1.6.0
libarchive-c                   2.9
llvmlite                       0.43.0
locket                         0.2.1
lxml                           4.8.0
Markdown                       3.3.4
markdown-it-py                 3.0.0
MarkupSafe                     3.0.2
matplotlib                     3.5.1
matplotlib-inline              0.1.2
mccabe                         0.6.1
mdurl                          0.1.2
mistune                        0.8.4
mkl-fft                        1.3.1
mkl-random                     1.2.2
mkl-service                    2.4.0
mmcv                           1.7.2
mmdet                          2.28.2
mmengine                       0.10.5
mock                           4.0.3
moviepy                        1.0.3
mpmath                         1.2.1
msgpack                        1.0.2
multidict                      5.2.0
multipledispatch               0.6.0
munkres                        1.1.4
mypy-extensions                0.4.3
navigator-updater              0.2.1
nbclassic                      0.3.5
nbclient                       0.5.13
nbconvert                      6.4.4
nbformat                       5.3.0
nest-asyncio                   1.5.5
networkx                       2.7.1
ninja                          1.11.1.2
nltk                           3.7
nodeenv                        1.9.1
nose                           1.3.7
notebook                       6.4.8
numba                          0.60.0
numexpr                        2.8.1
numpy                          1.24.2
numpydoc                       1.2
nuscenes-devkit                1.1.11
nvidia-cublas-cu11             11.11.3.6
nvidia-cuda-cupti-cu11         11.8.87
nvidia-cuda-nvrtc-cu11         11.8.89
nvidia-cuda-runtime-cu11       11.8.89
nvidia-cudnn-cu11              9.1.0.70
nvidia-cufft-cu11              10.9.0.58
nvidia-curand-cu11             10.3.0.86
nvidia-cusolver-cu11           11.4.1.48
nvidia-cusparse-cu11           11.7.5.86
nvidia-nccl-cu11               2.20.5
nvidia-nvtx-cu11               11.8.86
oauthlib                       3.2.2
olefile                        0.46
omegaconf                      2.3.0
opencv-contrib-python-headless 4.8.0.76
opencv-python                  4.10.0.84
opencv-python-headless         4.8.0.76
openpyxl                       3.0.9
packaging                      24.1
pandas                         1.4.2
pandocfilters                  1.5.0
panel                          0.13.0
param                          1.12.0
paramiko                       3.4.0
parsel                         1.6.0
parso                          0.8.3
partd                          1.2.0
PasteDeploy                    3.1.0
pathspec                       0.7.0
patsy                          0.5.2
pbkdf2                         1.3
peft                           0.11.1
pep8                           1.7.1
pexpect                        4.8.0
pickleshare                    0.7.5
pillow                         10.3.0
pip                            23.3.2
pkginfo                        1.8.2
plaster                        1.1.2
plaster-pastedeploy            1.0.1
platformdirs                   4.2.2
plotly                         5.6.0
pluggy                         1.0.0
plumbum                        1.8.3
poyo                           0.5.0
pre_commit                     4.0.1
proglog                        0.1.10
prometheus-client              0.13.1
prompt-toolkit                 3.0.20
Protego                        0.1.16
protobuf                       3.20.1
psutil                         5.9.4
ptyprocess                     0.7.0
pure-eval                      0.2.2
py                             1.11.0
pyasn1                         0.4.8
pyasn1-modules                 0.2.8
pycocotools                    2.0.8
pycocotools-fix                2.0.0.9
pycodestyle                    2.7.0
pycosat                        0.6.3
pycparser                      2.22
pyct                           0.4.6
pycurl                         7.44.1
pydantic                       2.7.4
pydantic_core                  2.18.4
PyDispatcher                   2.0.5
pydocstyle                     6.1.1
pyerfa                         2.0.0
pyflakes                       2.3.1
Pygments                       2.15.1
PyHamcrest                     2.0.2
PyJWT                          2.1.0
pylint                         2.9.6
pyls-spyder                    0.4.0
PyNaCl                         1.5.0
pyodbc                         4.0.32
pyOpenSSL                      23.2.0
pyparsing                      3.1.0
pyquaternion                   0.9.9
pyramid                        2.0.2
pyramid-mailer                 0.15.1
pyrsistent                     0.18.0
PySocks                        1.7.1
pytest                         7.1.1
python-dateutil                2.8.2
python-dotenv                  1.0.1
python-lsp-black               1.0.0
python-lsp-jsonrpc             1.0.0
python-lsp-server              1.2.4
python-multipart               0.0.19
python-slugify                 5.0.2
python-snappy                  0.6.0
python3-openid                 3.2.0
pytz                           2021.3
pyviz-comms                    2.0.2
PyWavelets                     1.3.0
pyxdg                          0.27
PyYAML                         6.0.1
pyzmq                          22.3.0
QDarkStyle                     3.0.2
qstylizer                      0.1.10
QtAwesome                      1.0.3
qtconsole                      5.3.0
QtPy                           2.0.1
queuelib                       1.5.0
ray                            2.30.0
referencing                    0.35.1
regex                          2024.5.15
repoze.sendmail                4.4.1
requests                       2.28.2
requests-file                  1.5.1
requests-oauthlib              2.0.0
rich                           13.9.4
rich-toolkit                   0.12.0
rope                           0.22.0
rotary-embedding-torch         0.5.3
rpds-py                        0.18.1
rpyc                           6.0.0
rsa                            4.7.2
Rtree                          0.9.7
ruamel-yaml-conda              0.15.100
s3transfer                     0.5.0
safetensors                    0.4.3
scikit-image                   0.19.2
scikit-learn                   1.1.3
scikit-learn-intelex           2021.20220215.212715
scipy                          1.9.3
Scrapy                         2.6.1
seaborn                        0.11.2
SecretStorage                  3.3.1
Send2Trash                     1.8.0
sentencepiece                  0.2.0
service-identity               18.1.0
setuptools                     61.2.0
Shapely                        1.8.5.post1
shellingham                    1.5.4
sip                            4.19.13
six                            1.16.0
smart-open                     5.1.0
sniffio                        1.3.1
snowballstemmer                2.2.0
sortedcollections              2.1.0
sortedcontainers               2.4.0
soupsieve                      2.5
Sphinx                         4.4.0
sphinxcontrib-applehelp        1.0.2
sphinxcontrib-devhelp          1.0.2
sphinxcontrib-htmlhelp         2.0.0
sphinxcontrib-jsmath           1.0.1
sphinxcontrib-qthelp           1.0.3
sphinxcontrib-serializinghtml  1.1.5
spyder                         5.1.5
spyder-kernels                 2.1.3
SQLAlchemy                     1.4.32
stack-data                     0.2.0
starlette                      0.37.2
statsmodels                    0.13.2
sympy                          1.12
tables                         3.6.1
tabulate                       0.8.9
TBB                            0.2
tblib                          1.7.0
tenacity                       8.0.1
tensorboard                    2.11.2
tensorboard-data-server        0.6.1
tensorboard-plugin-wit         1.8.1
termcolor                      2.4.0
terminado                      0.13.1
terminaltables                 3.1.10
testpath                       0.5.0
text-unidecode                 1.3
textdistance                   4.2.1
threadpoolctl                  3.2.0
three-merge                    0.1.1
tifffile                       2021.7.2
timm                           0.9.16
tinycss                        0.4
tldextract                     3.2.0
tokenizers                     0.15.2
toml                           0.10.2
tomli                          2.0.1
toolz                          0.11.2
torch                          2.4.0+cu118
torchaudio                     2.4.0
torchvision                    0.19.0+cu118
tornado                        6.1
tqdm                           4.65.0
traitlets                      5.1.1
transaction                    5.0
transformers                   4.39.3
translationstring              1.4
triton                         3.0.0
Twisted                        22.2.0
typed-ast                      1.4.3
typer                          0.15.1
typing_extensions              4.12.2
ujson                          5.1.0
Unidecode                      1.2.0
urllib3                        1.26.16
uvicorn                        0.29.0
uvloop                         0.21.0
velruse                        1.1.1
venusian                       3.1.1
virtualenv                     20.26.3
w3lib                          1.21.0
watchdog                       2.1.6
watchfiles                     1.0.0
wcwidth                        0.2.13
webencodings                   0.5.1
WebOb                          1.8.9
websocket-client               0.58.0
websockets                     14.1
Werkzeug                       2.3.6
wheel                          0.37.1
widgetsnbextension             3.5.2
wrapt                          1.16.0
WTForms                        3.2.1
wtforms-recaptcha              0.3.2
wurlitzer                      3.0.2
xarray                         0.20.1
xformers                       0.0.27.post2+cu118
xlrd                           2.0.1
XlsxWriter                     3.0.3
yapf                           0.40.2
yarl                           1.6.3
zict                           2.0.0
zipp                           3.19.2
zope.deprecation               5.0
zope.interface                 5.4.0
zope.sqlalchemy                3.1
`

**Comment by flymin** [comment]
Cloud you try
```python
 from apex.normalization import FusedRMSNorm
```
from your env? Will it raise any error?

**Comment by wang-kangkang** [comment]
> Cloud you try
> 
> ```python
>  from apex.normalization import FusedRMSNorm
> ```
> 
> from your env? Will it raise any error?

[root@********* ]# python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from apex.normalization import FusedRMSNorm
>>> type(FusedRMSNorm)
<class 'type'>
it seems no problem.
i see a solver in : https://github.com/hpcaitech/Open-Sora/issues/521#issuecomment-2182295918
can i change the shardformer to False? https://github.com/flymin/MagicDriveDiT/blob/main/configs/magicdrive/train/stage1_1x224x400_stdit3_CogVAE_noTemp_xCE_wSST_bs4_lr8e-5.py#L135

**Comment by flymin** [comment]
Hi,

Can you provide the output from these python lines?
```python
from transformers import T5EncoderModel
print(T5EncoderModel.from_pretrained("./pretrained/t5-v1_1-xxl"))
```
Please replace the path to your local path for t5 encoder.

**Comment by flymin** [comment]
The output seems fine as every `*layer_norm` is an instance of `FusedRMSNorm`.

Cloud you please print the `module.__class__.__name__` from [this line](https://github.com/flymin/MagicDriveDiT/blob/b2f7bca30a0c5e44b88f8fdbebfb0ec30a69d81e/magicdrivedit/acceleration/shardformer/modeling/t5.py#L31)? You can launch the code with only 1 GPU to debug.

**Comment by flymin** [comment]
I think I have found the output from your first log, which is `T5LayerNorm`
> [rank3]: RuntimeError: Failed to replace layer_norm of type T5LayerNorm with T5LayerNorm with the exception

In this case, please double check your python env.

One possible reason is that your are launching the code with a different env from the command `python`, becuase if this line
```python
 from apex.normalization import FusedRMSNorm
```
does not raise any error, `transformers` will use `FusedRMSNorm` in t5 encoder (as your command line output), rather than `T5LayerNorm` from your first error log.

**Comment by wang-kangkang** [comment]
> The output seems fine as every `*layer_norm` is an instance of `FusedRMSNorm`.
> 
> Cloud you please print the `module.__class__.__name__` from [this line](https://github.com/flymin/MagicDriveDiT/blob/b2f7bca30a0c5e44b88f8fdbebfb0ec30a69d81e/magicdrivedit/acceleration/shardformer/modeling/t5.py#L31)? You can launch the code with only 1 GPU to debug.



> The output seems fine as every `*layer_norm` is an instance of `FusedRMSNorm`.
> 
> Cloud you please print the `module.__class__.__name__` from [this line](https://github.com/flymin/MagicDriveDiT/blob/b2f7bca30a0c5e44b88f8fdbebfb0ec30a69d81e/magicdrivedit/acceleration/shardformer/modeling/t5.py#L31)? You can launch the code with only 1 GPU to debug.

the python environment earlier was lost...  i think the problem is the Colossalai is not installed correctly or complete. it maybe my fault.
You are very proactive, thank you very much.
