### ISSUE TITLE
Seeking Advice on Memory Optimization and Multi-GPU Training

### ISSUE THREAD

**Issue by jiangchaokang** [flymin/MagicDriveDiT#11]
I encountered some technical challenges while implementing your work and would greatly appreciate your guidance. My concerns primarily focus on two aspects:

1. Memory Optimization:
While training my own dataset, I frequently face memory insufficiency issues. Although I've reduced the video frame sequence from 65 to 49 frames, out-of-memory errors still occur occasionally. I would like to know if there are any recommended optimization strategies besides reducing frame count?

2. Multi-machine Training Adaptation:
I plan to train my dataset using multiple machines equipped with 49GB GPUs. Currently, the ColossalAI framework seems unable to adapt well to case where GPU memory is limited but Large number of GPUs. 

Could you please provide guidance on:
- Which specific code sections or configurations need modification?
- How should these modifications be implemented to enable successful multi-machine, multi-GPU training on 49GB GPUs?

Is it feasible to simply adjust accumulation_steps?

Thank you for your time and expertise.

**Comment by flymin** [comment]
Hi,

Even though you have closed the issue, I have some information to post here, which may be helpful for others.

For the diffusion process: As tested [here](https://github.com/flymin/MagicDriveDiT/blob/main/doc/FAQ.md#q21-minimum-gpu-memory-requirements-for-inference). `sp_size` is the most useful technique to reduce memory consumption on a single GPU. Besides, ColossalAI provides zero2, which can shard some memory usage across more GPUs, but there is no zero3/fsdp, so the requirement for minimum GPU memory is still high.

However, one may notice that the most critical consumption is the VAE encoding/decoding. In this case:
1. For frame length: We use `micro_frame_size` [here](https://github.com/flymin/MagicDriveDiT/blob/b2f7bca30a0c5e44b88f8fdbebfb0ec30a69d81e/configs/magicdrive/train/stage3_higher-b-v3.1-12Hz_stdit3_CogVAE_boxTDS_wCT_xCE_wSST_bs4_lr1e-5_sp4simu8.py#L248C22-L248C38) to keep a low consumption for encoding (decoding-part is down by the design of CogVAE).
2. For resolution: It is possible to use "tiling" on both encoding and decoding. We have incorporated the "tiling decode", while the tiling encoding has been implemented [here](https://github.com/huggingface/diffusers/blob/ec9bfa9e148b7764137dd92247ce859d915abcb0/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py#L1309). Even so, "tiling" is not a lossless algorithm which only approximates the original results and significantly slow down the process. We did not test "tiled" training.
3. Finally, if only train on limited samples, please consider pre-processing (encode) the original data into latents. This is very helpful for speeding up the training and avoiding the memory consumption from VAE & Text Encoder.
