### ISSUE TITLE
About camera paramerters and training

### ISSUE THREAD

**Issue by trkRingo** [flymin/MagicDriveDiT#14]
Thanks for this excellent work！I have the following questions:

1. During inference, can I directly use a new set of camera parameters to generate reasonable video?

2. When training on a custom dataset, is it a good way to fine-tune based on the MagicDriveDiT Checkpoints provided, or just train the three stages from scratch?

Looking forward to your reply!

**Comment by flymin** [comment]
Hi,

1. We haven't tried this, you may give it a try. From our previous experiments on UNet, changing cameras' ext/int may not work.
2. Please consider fine-tuning first. Training from scratch will cost a lot of computation resources.

**Comment by trkRingo** [comment]
Thanks for your reply!
